name: pallet_manager
version: 1.0.0+1
description: A pallet inventory and analytics management app.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_lints: ^5.0.0
  async: ^2.12.0
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  lints: ^5.1.1
  material_color_utilities: ^0.11.1
  vm_service: ^14.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true